spring:
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/personal-finance
    username: postgres
    password: admin

  flyway:
    clean-disabled: false
    baseline-on-migrate: false