spring:
  application:
    name: pf-data-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/personal-finance}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 day

cors:
  allowed-origins: "*"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [TraceID:%X{correlationId}] %logger{36} - %msg%n"
  level:
    root: info
    com.mayureshpatel.pfdataservice: debug
    org.springframework.web: info
    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace
