spring:
  application:
    name: pf-data-service

  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  flyway:
    locations: classpath:db/migration
    baseline-version: 1

logging:
  level:
    org.springframework.jdbc.core: debug