spring:
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/personal-finance
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET search_path TO public

  jdbc:
    template:
      query-timeout: 5s

  flyway:
    clean-disabled: false
    baseline-on-migrate: false

mapstruct:
  defaultComponentModel: spring